version: '3.8'

services:
  compositor-catolico:
    build: .
    container_name: compositor-catolico
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=development
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - compositor-network

  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: compositor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - compositor-catolico
    restart: unless-stopped
    networks:
      - compositor-network

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  compositor-network:
    driver: bridge
